spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/yalcoestore_v1
#    url: jdbc:postgresql://localhost:5432/yalcoestore_v1
    url: jdbc:postgresql://localhost:6666/yalcoestore_docker
    username: yalcoestore
    password: yalcoestore
    driver-class: org.postgresql.Driver
  liquibase:
    enabled: true
  application:
    name: facility
