--liquibase formatted sql
--changeset yappaz:create
CREATE TABLE FACILITY(
    ID BIGSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    COUNTRY VARCHAR(512) NOT NULL,
    CITY VARCHAR(512) NOT NULL,
    STREET VARCHAR(512) NOT NULL,
    STREET_NUMBER VARCHAR(64) NOT NULL,
    POST_CODE VARCHAR(256) NOT NULL,
    LATITUDE DECIMAl NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
    TYPE VARCHAR(256) NOT NULL,
    STATUS VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CREATED_BY VARCHAR(512) NOT NULL,
    OPENED_IN TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_BY VARCHAR(512) NOT NULL
);